[package]
name = "kiln"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A custom static site generator"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
jiff = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }
tempfile = "3"
